# Generated by Django 2.2.4 on 2019-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
